http:
    routers:
        insecurerouter:
            rule: "Host(`your.domain.com`)"
            service: apoioBackend
        allbackendrouter:
            rule: "Host(`your.domain.com`)"
            service: apoioBackend
            tls:
                certResolver: letsencrypt
                options: tlsoptions
    services:
        apoioBackend:
            loadBalancer:
                healthCheck:
                    path: /botflix/login/
                    interval: 10s
                    timeout: 3s
                servers:
                    - url: "http://IPORDOMAIN:PORT/"

tls:
    options:
        tlsoptions:
            minVersion: VersionTLS12
