# Static configuration
entryPoints:
    insecure:
        address: :80
    secure:
        address: :443

certificatesResolvers:
    letsencrypt:
        acme:
            email: your@email.com
            storage: acme.json
            httpChallenge:
                entryPoint: insecure
            
providers:
   file:
      filename: /etc/traefik/tls.yaml
      watch: true

api:
   dashboard: true
   insecure: true
