# Static configuration
entryPoints:
    insecure:
        address: :80
    secure:
        address: :443

certificatesResolvers:
    letsencrypt:
        acme:
            email: leandro@apoioassistencia24horas.com.br
            storage: acme.json
            httpChallenge:
                entryPoint: insecure
            
#traefikdemo.ddns.net
providers:
   # Enable the file provider to define routers / middlewares / services in file
   file:
      filename: /etc/traefik/tls.yaml
      watch: true

api:
   dashboard: true
   insecure: true
